name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: 'npm'
      - name: Lint and build
        run: |
          npm ci
          npm run lint
          npm run build
        env:
          CI: true
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: dist
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: github.ref == 'refs/heads/main'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: 'Website updated!'
          SLACK_MESSAGE: ${{ github.event.head_commit.message }}
          SLACK_USERNAME: 'Github'
          SLACK_ICON: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
      - name: Slack Notification on Failure
        if : ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: 'Website updated!'
          SLACK_MESSAGE: ${{ github.event.head_commit.message }}
          SLACK_USERNAME: 'Github'
          SLACK_ICON: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
